version: "3.9"

services:
  glance:
    container_name: glance
    image: glanceapp/glance
    volumes:
      - /home/timothy/HomeLab/Timothy/Glance/config:/app/config
    ports:
      - 8081:8080
    restart: unless-stopped
