pages:
  - name: Home
    width: wide
    columns:
      - size: small
        widgets:
          !include: ./f1_extensions/f1_next_race.yml

          !include: ./f1_extensions/f1_constructors_championship.yml

          !include: ./f1_extensions/f1_drivers_championship.yml

          - type: group
            widgets:
              - type: reddit
                cache: 1h
                subreddit: formula1
                style: vertical-cards
                limit: 3

      - size: full
        widgets:
          - type: search
            search-engine: google
            autofocus: true

          - type: bookmarks
            groups:
              - title: General
                links:
                  - title: Github
                    url: https://github.com/
                  - title: Amazon
                    url: https://www.amazon.ca/
                  - title: Movie Rankings
                    url: https://docs.google.com/spreadsheets/d/1d-YPy20QbiuzhKRq7IFGd5rfE0Iq9imoFgyNbzKo1uc/edit?usp=sharing
              - title: Entertainment
                links:
                  - title: Plex
                    url: https://app.plex.tv/desktop/#!/
                  - title: YouTube
                    url: https://www.youtube.com/
              - title: Social
                links:
                  - title: Reddit
                    url: https://old.reddit.com/
                  - title: Twitter
                    url: https://x.com/home

#          - type: custom-api
#            title: Uptime Kuma
#            url: http://uptime.winston-server.com/api/status-page/services
#            subrequests:
#              heartbeats:
#                url: http://uptime.winston-server.com/api/status-page/heartbeat/services
#            cache: 10m
#            template: |
#              {{ $hb := .Subrequest "heartbeats" }}
#
#              {{ if not (.JSON.Exists "publicGroupList") }}
#              <p class="color-negative">Error reading response</p>
#              {{ else if eq (len (.JSON.Array "publicGroupList")) 0 }}
#              <p>No monitors found</p>
#              {{ else }}
#
#              <ul class="dynamic-columns list-gap-8">
#                {{ range .JSON.Array "publicGroupList" }}
#                {{ range .Array "monitorList" }}
#                {{ $id := .String "id" }}
#                {{ $hbArray := $hb.JSON.Array (print "heartbeatList." $id) }}
#                {{ $latest := index $hbArray (toInt (sub ((len $hbArray) | toFloat) 1)) }}
#                <div class="flex items-center gap-12">
#                  <a class="size-title-dynamic color-highlight text-truncate block grow" href="http://uptime.winston-server.com/dashboard/{{ $id }}"
#                    target="_blank" rel="noreferrer">
#                    {{ .String "name" }} </a>
#                  {{ if eq ($latest.Int "status") 1 }}
#                  <div>{{ $latest.Int "ping" }}ms</div>
#                  <div class="monitor-site-status-icon-compact" title="OK">
#                    <svg fill="var(--color-positive)" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
#                      <path fill-rule="evenodd"
#                        d="M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16Zm3.857-9.809a.75.75 0 0 0-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 1 0-1.06 1.061l2.5 2.5a.75.75 0 0 0 1.137-.089l4-5.5Z"
#                        clip-rule="evenodd"></path>
#                    </svg>
#                  </div>
#                  {{ else }}
#                  <div><span class="color-negative">DOWN</span></div>
#                  <div class="monitor-site-status-icon-compact" title="{{ if $latest.Exists " msg" }}{{ $latest.String "msg" }}{{ else
#                    }}Error{{ end }}">
#                    <svg fill="var(--color-negative)" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
#                      <path fill-rule="evenodd"
#                        d="M8.485 2.495c.673-1.167 2.357-1.167 3.03 0l6.28 10.875c.673 1.167-.17 2.625-1.516 2.625H3.72c-1.347 0-2.189-1.458-1.515-2.625L8.485 2.495ZM10 5a.75.75 0 0 1 .75.75v3.5a.75.75 0 0 1-1.5 0v-3.5A.75.75 0 0 1 10 5Zm0 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"
#                        clip-rule="evenodd"></path>
#                    </svg>
#                  </div>
#                  {{ end }}
#                </div>
#                {{ end }}
#                {{ end }}
#              </ul>
#              {{ end }}

          - type: videos
            cache: 1h
            style: grid-cards
            collapse-after-rows: 1
            limit: 5
            channels:
             - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
             - UCvSuRqKTSHw4c3LCHeuCiiw # Bearded Mechanic
             - UCa3t89CuxPJFX2vvgagRUYw # Sam Reid
             - UC4PooiX37Pld1T8J5SYT-SQ # GMM


          - type: group
            widgets:
              - type: reddit
                cache: 2h
                limit: 3
                subreddit: edmonton
                show-thumbnails: true
              - type: reddit
                cache: 2h
                limit: 3
                subreddit: alberta
                show-thumbnails: true
              - type: reddit
                cache: 2h
                limit: 3
                subreddit: homelab
                show-thumbnails: true
              - type: reddit
                cache: 2h
                limit: 3
                subreddit: movies
                show-thumbnails: true

      - size: small
        widgets:
          - type: clock
            hour-format: 12h
            timezones:
             - timezone: Europe/London
               label: England
             - timezone: Europe/Stockholm
               label: Sweden
             - timezone: US/Central
               label: Dallas

          - type: weather
            location: Edmonton, Canada
            units: metric # alternatively "imperial"
            hour-format: 12h # alternatively "24h"
            # Optionally hide the location from being displayed in the widget
            # hide-location: true


          - type: markets
            cache: 15m
            markets:
              - symbol: VEQT.TO
                name: Vanguard Total World Equity
              - symbol: VFV.TO
                name: Vanguard S&P 500
              - symbol: TEC.TO
                name: TD Technology ETF


          - type: twitch-channels
            cache: 15m
            collapse-after: 3
            channels:
              - Northernlion
              - shxtou
              - sleepy
              - birlap
              - Squeex
              - p4perback
              - WhatAboutAndy



# To be added
  - name: Markets
    width: wide
    columns:
      - size: small
        widgets:

      - size: full
        widgets:

      - size: small
        widgets:

# To be added
  - name: Server
    width: wide
    columns:
      - size: small
        widgets:
          - type: bookmarks
            groups:
              - title: Services
                links:
                  - title: Sonarr
                    url: http://sonarr.winston-server.com
                  - title: Radarr
                    url: http://radarr.winston-server.com
                  - title: Pihole
                    url: http://pihole.winston-server.com/admin

      - size: full
        widgets:

      - size: small
        widgets:
         - type: releases
           repositories:
            - linuxserver/docker-plex
            - glanceapp/glance
            - pi-hole/pi-hole
