- type: custom-api
  title: Recently Watched
  cache: 30m
  url: http://${TAUTULLI_IP}:${TAUTULLI_PORT}/api/v2?apikey=${TAUTULLI_API_KEY}&cmd=get_home_stats&stat_id=last_watched
  template: |
    <ul class="list collapsible-container" data-collapse-after="5">
      {{ range $i, $v := .JSON.Array "response.data.rows" }}
        {{ $lastWatch := printf "%d" ($v.Int "last_watch") }}
        <li class="flex items-center gap-2" style="padding: 0.5rem 0; border-bottom: 1px solid var(--color-border);">
          <img src="http://${TAUTULLI_IP}:${TAUTULLI_PORT}/api/v2?apikey=${TAUTULLI_API_KEY}&cmd=pms_image_proxy&img={{ $v.String "thumb" }}" 
             alt="thumb"
             style="width: 50px; margin-right: 1.5rem;"
             class="rounded w-10 h-10 object-cover" />
          <div class="min-width-0 grow">
            {{ $type := $v.String "media_type" }}
            {{ $isEpisode := eq $type "episode" }}
            {{ $isMovie := eq $type "movie" }}
            {{ if $isEpisode }}
              <div class="color-highlight" title="{{ $v.String "grandchild_title" }}">
                {{ $v.String "grandparent_title" }} - S{{ printf "%02d" ($v.Int "parent_media_index") }}E{{ printf "%02d" ($v.Int "media_index") }}
              </div>
            {{ else if $isMovie }}
              <div class="color-highlight" title="{{ $v.String "title" }}">
                {{ $v.String "title" }} ({{ $v.Int "year" }})
              </div>
            {{ end }}
            <div class="color-primary">
              {{ $v.String "friendly_name" }} • <span {{ parseRelativeTime "unix" $lastWatch }}></span> ago
            </div>
          </div>
          {{ $serverID := "${SERVER_ID}" }}
          {{ $ratingKey := $v.String "rating_key" }}
          <a href="https://app.plex.tv/desktop/#!/server/{{ $serverID }}/details?key=%2Flibrary%2Fmetadata%2F{{ $ratingKey }}" target="_blank" 
            class="color-primary">
            ▶
          </a>
        </li>
      {{ end }}
    </ul>