version: "3.9"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true
    environment:
      EULA: "TRUE"
      MEMORY: 8G
      TYPE: VANILLA
      VIEW_DISTANCE: 32
      VERSION: "1.21.7"
      MOTD: "Meow =^-^="
      DIFFICULTY: normal
      OPS: |
        SLEEBYSKY
      ICON: https://avatars.githubusercontent.com/u/52394699?v=4
      OVERRIDE_ICON: TRUE
    volumes:
      - ./data:/data
    restart: unless-stopped

  atm10:
    build: 
      context: ./minecraft-atm10
      dockerfile: Dockerfile
    container_name: minecraftmodded
    volumes:
      - ./minecraft-atm10/data:/app/data
    ports:
      - "25566:25565"
    environment: 
      EULA: "TRUE"
      MEMORY: 10G
      VIEW_DISTANCE: 16
      OPS: |
        PoisonIvysoar
        IvySauryn
    tty: true
    stdin_open: true
    restart: unless-stopped
      
