version: "3.9"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - LANG=en
      - WG_HOST=wgeasy.winston-server.com
      - PASSWORD_HASH=$$2a$$12$$vGQPEAFP/cQc7bFPEBJJHubvI1sU6xi3s7hT4eAJFubiD79ZWYxmm
      - PORT=51821
      - WG_PORT=51820
      - WG_DEFAULT_DNS=192.168.0.80
    volumes:
      - /home/sky/docker-compose/wg-easy/:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge
