version: '3.9'

services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    container_name: ghostfolio
    depends_on:
      - db
      - redis
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - ACCESS_TOKEN_SALT=${ACCESS_TOKEN_SALT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    restart: unless-stopped
    networks:
      - ghostfolio-network

  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=ghostfolio
      - POSTGRES_USER=ghostfolio
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ghostfolio-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: unless-stopped
    networks:
      - ghostfolio-network

volumes:
  db-data:

networks:
  ghostfolio-network:
    driver: bridge
